# Generated by Django 5.0.1 on 2024-01-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_activitati_host_message_activitati_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitati',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='topic',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
