# Generated by Django 5.0.1 on 2024-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_activitati_date_time_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitati',
            name='rating_intensity',
            field=models.IntegerField(default=0),
        ),
    ]
