# Generated by Django 5.0.1 on 2024-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
    ]
