# Generated by Django 5.0.1 on 2024-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_goal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='topics',
            field=models.ManyToManyField(blank=True, to='base.topic'),
        ),
    ]
