# Generated by Django 5.0.1 on 2024-01-05 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_goal_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitati',
            name='duration_in_seconds',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='activitati',
            name='hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='activitati',
            name='minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='activitati',
            name='seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
