# Generated by Django 5.0.1 on 2024-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_activitati_duration_in_seconds_activitati_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitati',
            name='duration_in_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
