# Generated by Django 5.0.1 on 2024-01-05 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_activitati_duration_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitati',
            name='hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
